### ISSUE TITLE
HCCL 로고 색 통일성

### ISSUE THREAD

**Issue by dayoung-jeong** [Hanyang-HCC-Lab/Hanyang-HCC-Lab#18]
상단 로고는 "human-centered" 에 색이 들어가 있고
하단 로고는  "human" 에 색이 들어가 있어서 동일한 색으로 변경하면 좋을 것 같습니다.

**Comment by jaehoonkimm** [comment]
@mmmymung0331 어떤걸로 통일하면 좋을까요?

**Comment by mmmymung0331** [comment]
human에만 색이 들어가 있는 것으로 바꿀까요?

**Comment by jaehoonkimm** [comment]
@mmmymung0331 "-" 부분이 약간 애매한 느낌도 들어서, 이 부분 어떻게 처리하면 더 좋을지 의견 주시면 감사하겠습니다. 

![스크린샷 2022-11-04 오전 10 52 48](https://user-images.githubusercontent.com/43606451/199868264-9a05ea83-db8a-43a5-980f-cc340484ec86.png)
![스크린샷 2022-11-04 오전 10 52 59](https://user-images.githubusercontent.com/43606451/199868266-ee9a192e-2996-464c-86dd-426016ddd6d3.png)
